Collaborative editing
ForumMagnum/ForumMagnum pull request #4379
Opened 2021-12-14 21:12 UTC by jimrandomh

2021-12-15 22:43 UTC, Raemon commented
Relatively minor note, but it's unintuitive to me that the "confirm" button isn't in the bottom-right of the sharing widget.

![image](https://user-images.githubusercontent.com/3246710/146276274-f21dfd31-1608-4ab2-83d4-3d38b90d35eb.png)

2021-12-15 22:46 UTC, Raemon commented
Shouldn't be blocking, but, it'd be nice if Shared Posts showed up somewhere on my Profile page. (or something. They might be somewhere else and I haven't run into them yet)

2021-12-15 22:52 UTC, Raemon commented
I notice that changes to "user can edit" don't take effect on my test-shared-user's page until I refresh. Shouldn't be blocking I think but does me I effectively can't stop users from editing once they've started, and probably a fairly major thing to fix soon.

2021-12-17 01:08 UTC, Raemon requested changes
It... looks like I can't type into comment fields! I've run `yarn install`, and `yarn rebuild-reinstall-ckeditor`

Commenting also isn't working on lessestwrong, where I have deployed the branch.

2021-12-18 21:24 UTC, jpaddison3 commented
Thanks for building this, Jim! UI comments:

 * I don't love the placement of the share button.
 * Sharing settings components is very in need of whitespace
 * So are the buttons for editing / deleting your own side-comment
 * Trying to submit a comment with ⌘-Enter submits the whole post form
 * The CollaborateOnPost route should set a white background
 * It's super cool that this is so realtime 😄
 * When you hover over another users cursor marker, it expands a line to the right that's clearly supposed to have their username, but the username is missing (it's in the html tho)
 * Another whitespace request: between the "by $USERNAME" and the circles telling you who's connected (this only appears when you're not the author) [and probably less between the title and "by $USERNAME"]
 * There should be a loading spinner when the editor is loading.

And some requests:

 * Could I get more context in the form of a PR description?
 * Can you say more about what's up with configuring ckeditor on the ckeditor side? I think our ckeditor keys are just copies of yours. (I don't remember, but have asked Oli.)
 * This appears to have the new user form page as well? That couldn't be factored out into a separate PR, could it?

2021-12-20 15:33 UTC, jpaddison3 commented
I think the UI should really warn you quite hard if you try to add an image to a non-online group. I know this is hard to do, but at the very least, hack it to say Online-Groups-Only as a title or something. (Maybe with a form group)

2021-12-21 21:57 UTC, jpaddison3 commented on packages/lesswrong/components/posts/PostsPage/PostActions.tsx
> +        {editLink}
Good change.

2022-04-07 16:51 UTC, merged