Review Voting migration 2
ForumMagnum/ForumMagnum pull request #4482
Opened 2022-01-13 22:38 UTC by Raemon

This creates a second set of fields for the second/and/or/final round of voting (I'm not sure if we want 2 or 3 voting rounds. I think it's useful to store them as separate fields so that we can see how post rankings evolved over the course of the review phases)

2022-01-14 13:45 UTC, jpaddison3 commented
I'm sorry, I'm not sure what these are for. Why do we need to differentiate from the originals?

2022-01-14 13:45 UTC, jpaddison3 commented on packages/lesswrong/lib/collections/posts/schema.ts
> +  reviewVoteScoreHighKarma2: {
Right about here I'd put a comment explaining what these are for.

2022-01-14 13:45 UTC, jpaddison3 commented on packages/lesswrong/server/migrations/2022-01-12-updateQuadraticVotes-2.ts
> +registerMigration({
I assume this is entirely copy-pasta-ed without change and I don't need to review it?

2022-01-14 13:45 UTC, jpaddison3 commented on packages/lesswrong/server/migrations/2022-01-12-updateQuadraticVotes-2.ts
> +registerMigration({
(Copy pasta is fine here, IMO, as migrations are one and done in this codebase.)

2022-01-24 20:08 UTC, darkruby501 requested changes
I haven't reviewed the migration since I don't know what it's about.

WIth regard to the new fields, they need a clearer name than "2".

2022-01-24 20:08 UTC, darkruby501 commented on packages/lesswrong/lib/collections/posts/fragments.ts
> +    reviewVoteScoreHighKarma2
What, what's up with the 2? What does the 2 mean?

2022-01-24 20:08 UTC, darkruby501 commented on packages/lesswrong/lib/collections/posts/fragments.ts
> +    reviewVoteScoreHighKarma2
Okay, I see. I'd rename from "2" to "2ndRound"

2022-02-04 17:57 UTC, jpaddison3 approved these changes
I haven't tested this locally, but I believe if it runs and produces something that looks good, then it's probably good.

2022-02-04 17:57 UTC, jpaddison3 commented on packages/lesswrong/server/migrations/2022-01-30-updateFinal2020ReviewVotes.ts
> +    const primaryColor = "#5f9b65" // ea-forum-look-here
I get this when I go to run it and submit a separate PR. Thanks for calling it out.

2022-02-05 21:26 UTC, Raemon commented on packages/lesswrong/server/migrations/2022-01-12-updateQuadraticVotes-2.ts
> +import { registerMigration } from './migrationUtils';
Ah yeah. Thanks.

2022-02-05 21:27 UTC, Raemon commented
@jpaddison3 btw you requested changes so you'll need to approve

2022-02-07 04:39 UTC, darkruby501 approved these changes
I didn't read this in detail but nothing objectionable stuck out to me.

2022-02-07 07:34 UTC, merged