Add Manifold Markets embeds
ForumMagnum/ForumMagnum pull request #4907
Opened 2022-05-12 16:26 UTC by sipec

_Directly_ cribbed from OWID previews https://github.com/ForumMagnum/ForumMagnum/pull/4728

Uh, I haven't tested this yet cus I'm not a lightcone dev and thus don't have the credentials to spin up the local instance

2022-05-12 16:33 UTC, sipec commented on public/lesswrong-editor/src/ckeditor.js
> +				<div data-manifold-id="${longslug}" class="manifold-preview">
I'm actually not sure what all these data id custom attributes are for!
Unless there's lesswrong-specfic reasons the other embeds have it, the iframe alone should suffice

2022-05-12 18:34 UTC, jpaddison3 commented
> Uh, I haven't tested this yet cus I'm not a lightcone dev and thus don't have the credentials to spin up the local instance. Either someone else needs to take it from here, or I'll need to get unblocked on setup.

You can run the instance with a local database! I coincidentally just made an update to the readme that should make that clearer. No credentials required. Let me know if you do think I'm wrong — I know some things like search won't work, but you should be able to test this just fine.

2022-05-12 20:48 UTC, Xodarap commented
Thanks for submitting this!

I would update the size of the embed (or change how you are populating the iframe on your end):

<img width="289" alt="image" src="https://user-images.githubusercontent.com/221511/168162714-44c60bc4-7726-451a-842c-0bf97127619e.png">

also remember to run `yarn rebuild-reinstall-ckeditor` and commit the build files.

2022-05-12 20:49 UTC, Xodarap requested changes
Please update the UI and commit the build files

2022-05-16 16:17 UTC, sipec commented
> Please update the UI

I've updated it now to be like the styling for the other embeds, but I still won't be able to test how it actually looks in context

2022-05-17 15:26 UTC, sipec commented
how long is the mongodb local setup supposed to take? it's been several hours and still inching along...

2022-05-18 21:58 UTC, Xodarap commented
This is still looks weird to me:

<img width="340" alt="image" src="https://user-images.githubusercontent.com/221511/169162719-499cff48-7424-4822-8765-28151fc965ed.png">


I think the Mongo set up should not take that long. Did it complete for you? I'm not sure what would be taking a long time – Mongo is slow, but it's not that slow.

2022-05-19 21:14 UTC, sipec commented
It did complete, I think now, but it's quite difficult to get the client to connect to the local server correctly. It keeps disconnecting

2022-05-20 17:54 UTC, Xodarap approved these changes

2022-05-20 18:02 UTC, merged

2022-05-20 19:25 UTC, Xodarap commented
@sipec Thanks for doing this! The change has now been deployed to the EA Forum. Want to make an announcement post? You could continue the proud tradition of copying OWID and do something similar to their post: https://forum.effectivealtruism.org/posts/PSmsGwk2kZbBXZgHi/new-forum-feature-preview-and-embed-our-world-in-data-charts

I'm not sure when LW will merge in your changes, but I would guess it's fairly soon.

2022-05-26 04:23 UTC, jaysonvirissimo commented
Oh heck yeah!