Add Table of Contents to Concepts page
ForumMagnum/ForumMagnum pull request #5403
Opened 2022-08-06 21:28 UTC by jimrandomh

Adds a table of contents to the Concepts (aka Topics, aka All Tags) page. This makes that page easier to navigate, and also makes the Random Tag feature much easier to find.

This adds a few options to configure how ToC is displayed, which are specific to LessWrong's Concepts page: specifically, on the LW concepts page in particular, the ToC downcases all-caps section headings, and limits the heading-depth. (Otherwise the "Theory  Concepts", "Applied Topics", and "Failure Modes" columns, seen in the screenshot, would all be in the ToC, and the overall ToC would be very long.) Note that I have not looked at this with the EA Forum's version of the page (Topics); I don't expect it to be buggy but I wouldn't be surprised if you want to micromanage the presentation of subheadings in a way that's analogous to (but different from) how I adjusted the subheadings for the LW Concepts page.

![Screen Shot 2022-08-06 at 14 20 50](https://user-images.githubusercontent.com/101191/183266464-6e9b1de8-a0f8-4298-8c3f-4b968f858bda.png)

2022-08-07 18:52 UTC, darkruby501 commented
Seems great. Man, so long ago we should have cleaned up the top of the page so those links and bullet points weren't just hackily part of the text form.

2022-08-11 23:10 UTC, Will-Howard requested changes
When I run this for the EA forum it looks like this (the centre column is collapsed to one side), I can't work out which bit is causing this but it definitely needs fixing before we can merge
<img width="1498" alt="Screenshot 2022-08-12 at 00 08 05" src="https://user-images.githubusercontent.com/77623106/184257163-568f0d74-0e76-4212-9843-ecd8fdc645c2.png">

2022-08-18 21:02 UTC, jimrandomh commented
Fixed the narrow-column issue (there was a width specified in the EA forum site-theme, which was limiting the combined central column+ToC width rather than the central column width as intended).

2022-08-23 10:24 UTC, Will-Howard approved these changes

2022-10-06 00:32 UTC, merged