Remove flexWrapEndRow to Tag Filter Settings
ForumMagnum/ForumMagnum pull request #6596
Opened 2023-01-28 21:57 UTC by Raemon

I think the new frontpage filters look unacceptably bad by default:

<img width="755" alt="image" src="https://user-images.githubusercontent.com/3246710/215292330-37baef94-d560-44a5-b430-79b79bbf228a.png">

If you remove the flexWrapEndRow div, it instead looks like this, which IMO is much better:
<img width="846" alt="image" src="https://user-images.githubusercontent.com/3246710/215292335-4a12a1d1-4f59-413c-9101-9c6ba9bc7a0d.png">

And AFAICT I can add ~2 tags with some filtering and it still looks pretty reasonable:
<img width="734" alt="image" src="https://user-images.githubusercontent.com/3246710/215292609-08502d26-38ad-4374-a68a-f2dfbc7cff98.png">

It's not until I add _three_ new tags that it starts looking weird. I agree this looks bad, but a) I honestly don't think it's _horrendously bad_ and meanwhile I predict only a teeny fraction of users are going to add 3 tags and see it looking like this in the first place.
<img width="806" alt="image" src="https://user-images.githubusercontent.com/3246710/215292639-914dacc4-3d07-4077-ac85-ad7415252188.png">

(This might be different on the EA Forum that has fewer tags by default, I'm not sure what that ends up looking like, could imagine forum-gating a solution here)

I futzed around with some other options to see if there was a "get the best of both worlds" option but couldn't find anything that seemed better. (I do still think it's not crazy to just conditionally-display the flexWrapEndRow if there are 3+ tags or something, I don't think it's as madness inducing as @jpaddison3 and @jimrandomh think. I agree it's at least a _little_ madness inducing, so just proposing this simple change instead for now)

2023-01-28 22:00 UTC, darkruby501 commented
It doesn't strike me as unacceptably bad, but the 3-tag state looks very clearly broken.

Nonetheless, I think I'm ok with this PR if EA Forum is/doesn't think it breaks things worse for them

2023-01-28 22:02 UTC, darkruby501 commented
We could rename AI -> "AI & Alignment" and that'd help a bit

2023-01-29 01:27 UTC, Raemon commented
I agree the three-tag state looks quite bad, I just don't expect it to come up very often. 

(Obviously it _would_ come up more often if we changed the name of AI to "AI & Alignment". I do _like_ that you can add ~2 tags without bumping up to 2 lines, so I'm somewhat inclined to keep it just "AI". I acknowledge that it'd be easier to notice it if it were a longer tag name, but I think if we set the default value to "reduced" it's less important to do that)

2023-01-30 16:40 UTC, jpaddison3 commented
This makes the default view of the EA Forum look terrible.
<img width="990" alt="image" src="https://user-images.githubusercontent.com/10352319/215539041-7ad39510-cfea-444c-96ca-f02c9f584c63.png">

Please do not merge without a Forum-gate. In addition, I have to express my personal disagreement with:
> I honestly don't think it's _horrendously bad_

And would recommend you find another solution.

2023-01-30 16:40 UTC, jpaddison3 requested changes
.

2023-01-30 16:49 UTC, jpaddison3 commented
(Your whole goal is to get people to use this feature more. That entails people adding tags?)

2024-08-17 22:30 UTC, closed without merging