Move bookmark link to post header
ForumMagnum/ForumMagnum pull request #6660
Opened 2023-02-08 16:30 UTC by jcmustin

This PR brings the bookmark link out of the post page actions dropdown and into the post header, while also making a few other styling changes to the secondary info section, in accordance with designs [here](https://www.figma.com/file/OD4vJlLuWriHqG1WJXY4LV/Q1.1-2023?node-id=127%3A2846&t=HfpqlBXA1NEuCe2E-0).
- Use a comment icon rather than "n comments"
- Remove ordinal from date (8th Feb 2023 -> 8 Feb 2023)
- Increase secondary info font size to unify styling with author name
- Make spacing before triple dot icon the same as other secondary info items
- Increase margin between secondary info and title on EA Forum to 16px (site-specific because the original margin was already site-specific)
- Minor modifications to menu item styling on the EA Forum

## Desktop
<img width="783" alt="image" src="https://user-images.githubusercontent.com/25752873/217577930-effbb09c-ce82-4901-9182-bcc3c02e1547.png">

## Mobile
<img width="393" alt="image" src="https://user-images.githubusercontent.com/25752873/217578019-179937b5-75bd-4b4f-8086-5fa70e830abd.png">

2023-02-09 09:38 UTC, agnesstenlund commented
This looks really really great @jcmustin 👏  thanks for the clear PR description too.

I only have one tiny design nit-pick: looks like the tooltip appears on the right, whereas it otherwise seems to appear below

https://user-images.githubusercontent.com/13235378/217773409-30c79ca7-158b-4028-9790-eaba821c65ac.mov


Also looks like we haven't yet made the naming change in the user menu + on the Frontpage (guessing this was intentional as it wasn't completely clear if we were moving from Bookmark to Saved)

![Screenshot 2023-02-09 at 10 31 02](https://user-images.githubusercontent.com/13235378/217773588-ec2aa217-3d41-48b6-b16d-15708c941c64.png)
![Screenshot 2023-02-09 at 10 30 35](https://user-images.githubusercontent.com/13235378/217773593-9ff03922-9e69-4272-93ce-5d08e54f8979.png)
![Screenshot 2023-02-09 at 10 37 19](https://user-images.githubusercontent.com/13235378/217774724-12e14a88-9b58-471e-b448-f9808b4cf0c6.png)

2023-02-13 21:11 UTC, s-cheng requested changes
Looks great, thanks!

1. Please address Agnes's comments
2. Last I saw on slack, LW wanted this to be forum-gated right? If that's no longer the case, then this needs some styling tweaks before it's ok to ship to LW. (Either way, please make sure to test this with `forumType` = LessWrong.)

LW current styling:
<img width="647" alt="Screen Shot 2023-02-13 at 4 01 45 PM" src="https://user-images.githubusercontent.com/9057804/218574618-3987ac59-e7ff-4a20-962b-b6f27a8122a4.png">

On this branch (prob just need to adjust the icon size?):
<img width="647" alt="Screen Shot 2023-02-13 at 4 01 09 PM" src="https://user-images.githubusercontent.com/9057804/218574666-152617ce-1ae0-415d-915b-c6d58195e611.png">

2023-02-13 21:14 UTC, s-cheng commented on packages/lesswrong/components/posts/PostsPage/PostsPagePostHeader.tsx
> +          </div>}
This button's font size is too small, plus we prob want to adjust the spacing between the icon and the label to be consistent:
<img width="647" alt="Screen Shot 2023-02-13 at 4 08 37 PM" src="https://user-images.githubusercontent.com/9057804/218575593-0ff2c877-f145-465c-9a6c-0813f820d980.png">

2023-03-29 12:09 UTC, jpaddison3 commented
@s-cheng, this should be assigned to you right?

2023-05-10 04:32 UTC, s-cheng approved these changes

2023-05-10 04:55 UTC, s-cheng commented
@agnesstenlund I'm gonna call this done for now, can you do a review? I think almost all the things from your figma are implemented, the main thing missing is the hover still decreases opacity instead of making the color darker, but I think we should just do that in another PR so we can finally merge this one in.

2023-05-14 11:04 UTC, merged