Remove save button from post header on EA forum
ForumMagnum/ForumMagnum pull request #7197
Opened 2023-05-16 09:02 UTC by Will-Howard

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1204610279041423) by [Unito](https://www.unito.io)

2023-05-16 09:50 UTC, agnesstenlund commented
I don't think we intended to remove the whole save button, just the label `Save` 😮  (but keep the icon)

2023-05-16 17:48 UTC, jpaddison3 requested changes

2023-05-16 17:48 UTC, jpaddison3 commented on packages/lesswrong/components/posts/PostsPage/PostsPagePostHeader.tsx
> -                <PostActionsButton post={post} includeBookmark={!isEAForum} />
This one definitely seems wrong?

2023-05-16 17:48 UTC, jpaddison3 commented on packages/lesswrong/components/posts/PostsPage/PostsPagePostHeader.tsx
> -          {isEAForum && <BookmarkButton post={post} variant='iconWithText' />}
Agree that this was not the intended behavior, and that we should be looking to remove the text instead.

2023-05-17 09:00 UTC, Will-Howard commented
> I don't think we intended to remove the whole save button, just the label Save

My bad, I'll change this

2023-05-26 11:18 UTC, oetherington approved these changes
👍 Works nicely.

A couple of things that would be nice though:

- There's no hover style - probably we should have the same hover style here that we have for the comments button next to it
- The tooltip placement should probably match the comments button too (`BookmarksButton` takes a placement prop so this should be easy)

2023-05-26 14:56 UTC, merged