LW nonhuman audio podcast styling
ForumMagnum/ForumMagnum pull request #7579
Opened 2023-07-15 02:06 UTC by Raemon

<img width="860" alt="image" src="https://github.com/ForumMagnum/ForumMagnum/assets/3246710/9078996f-64fc-4fbb-8bfc-438e8afa95c9">

2023-07-15 12:43 UTC, jpaddison3 requested changes

2023-07-15 12:43 UTC, jpaddison3 commented on packages/lesswrong/components/posts/PostsPage/PostsPagePostHeader.tsx
> +  const audioIcon = <LWTooltip title={'Listen to this post'} className={classNames(classes.togglePodcastContainer, {[classes.nonhumanAudio]: nonhumanAudio})}>
This has no conditional application for LW

2023-07-27 19:53 UTC, jpaddison3 commented
No objection from the EA Forum

2023-07-28 18:36 UTC, b0b3rt approved these changes

2023-07-28 18:51 UTC, merged