EA Tag hover over redesign
ForumMagnum/ForumMagnum pull request #8079
Opened 2023-10-25 12:51 UTC by oetherington

2023-10-26 10:02 UTC, oetherington commented on packages/lesswrong/components/tagging/TagTooltipWrapper.tsx
Replaced with `TagsTooltip`

2023-10-26 10:04 UTC, oetherington commented
@agnesstenlund This should be ready now.

The designs specified 7 lines for the preview, but we can't really cut it off based on the number of lines (like with the post tooltip) so we're using characters instead that seems to be _about_ 7 lines.

2023-11-07 17:18 UTC, s-cheng requested changes
Looks very nice on the EA Forum side! (Though I hope we add preview images at some point ^^)

LW looks quite broken - I'd like to test LW more thoroughly, so ask me for another review once you've fixed that side.
<img width="898" alt="Screen Shot 2023-11-07 at 12 15 46 PM" src="https://github.com/ForumMagnum/ForumMagnum/assets/9057804/f0c1beba-8f4a-41fd-ae33-7a68b0be5dfe">

2023-11-08 12:21 UTC, agnesstenlund commented
Looks perfect <3

2024-01-08 11:49 UTC, oetherington commented
@s-cheng I think everything here should be fixed now.

CC @agnesstenlund in case you want to take another look (but nothing should have changed for EA forum since you last looked except bug fixes).

@b0b3rt We created this PR a couple of months ago to redesign the tags tooltip on the EA forum, but in the process we broke the tooltip pretty badly for LW and fixing it got deprioritised in favour of other stuff. I think I've now fixed the problems on LW, but I'd appreciate if you could just give it a quick look in case I missed something (not super urgent though). Thanks!

2024-01-11 20:26 UTC, s-cheng commented
@oetherington Thanks! It's def less broken but I still see some discrepancies and I think it's important for us not to mess with LW's site. I noticed three small things:
1. Looks like there is additional padding in the LW tooltip now
2. Looks like the LW tooltip is aligned with the bottom of the tag name rather than the bottom of the tag pill now
3. Possibly the tag description is not getting truncated early enough? I'm not sure

Compare the version on LW prod:
![Screen Shot 2024-01-11 at 3 19 38 PM](https://github.com/ForumMagnum/ForumMagnum/assets/9057804/3eae5a8a-a60b-46b9-8c1b-020c71e5ff01)

With this branch:
<img width="517" alt="Screen Shot 2024-01-11 at 3 20 00 PM" src="https://github.com/ForumMagnum/ForumMagnum/assets/9057804/11745d7a-3300-4cce-8968-87ccbb9b998e">

2024-01-15 17:40 UTC, oetherington commented
@s-cheng Whoops - missed those! 1 and 2 are now fixed. 3 is the same as master.

AFAIK, the only difference now is that post titles/authors that are too long are now cutoff at the edge of the padding instead of extending all the way to the edge of the tooltip. I think the previous behaviour was actually just a bug and that it looks better this way, but I'll happily change it back if anybody from LW objects.

2024-01-15 19:57 UTC, s-cheng approved these changes
🙌

2024-01-16 19:38 UTC, merged