Add my dialogues to frontpage & dialogues page
ForumMagnum/ForumMagnum pull request #8119
Opened 2023-10-31 01:43 UTC by ben-pace

This adds a section called "My Draft Dialogues" to the frontpage, and a big section called "My Dialogues (Drafts & Published)" to the /dialogues page.

[Coauthored with Ruby.]

Screenshots below.

<img width="755" alt="Screen Shot 2023-10-30 at 6 37 45 PM" src="https://github.com/ForumMagnum/ForumMagnum/assets/24915924/15735b6b-ec8e-496d-95f0-ca47d4173663">

<img width="792" alt="Screen Shot 2023-10-30 at 6 39 20 PM" src="https://github.com/ForumMagnum/ForumMagnum/assets/24915924/8e7ce397-dddd-4d06-877b-74a970112733">

2023-10-31 17:54 UTC, b0b3rt commented on packages/lesswrong/components/dialogues/DialoguesList.tsx
> +      <div>These are dialogues that you are a coauthor on (including drafts and published dialogues).</div>
Do we want this to have the same language as the (same?) tooltip on the /dialogues page?

2023-10-31 17:55 UTC, b0b3rt commented on packages/lesswrong/server/repos/PostsRepo.ts
> +          WHERE p."collabEditorDialogue" IS TRUE AND ((UNNESTED->>'userId' = $1) OR (p."userId" = $1))
nit: for readability, break up `AND` clause onto its own line

2023-10-31 17:57 UTC, b0b3rt commented on packages/lesswrong/server/resolvers/postResolvers.ts
> +      return repos.posts.getMyActiveDialogues(currentUser._id, limit)
Technically this is safe, but if we're returning something in the shape of a `DbPost`, we should probably bother to pass it through `accessFilterMultiple` to validate access permissions

2023-10-31 17:58 UTC, b0b3rt approved these changes
yeah, this seems basically fine.

2023-10-31 18:24 UTC, b0b3rt requested changes

2023-10-31 18:24 UTC, b0b3rt commented on packages/lesswrong/server/resolvers/postResolvers.ts
> +  cacheMaxAgeMs: 1000 * 60 * 10, // 10 min
Don't cache results - turns out this is totally independent of any input

2023-10-31 18:25 UTC, darkruby501 commented on packages/lesswrong/components/dialogues/DialoguesPage.tsx
> +      <AnalyticsContext pageSectionContext="MyDialoguesList">
```suggestion
{renderMyDialogues && <AnalyticsContext pageSectionContext="MyDialoguesList">
```

2023-10-31 18:25 UTC, darkruby501 commented on packages/lesswrong/components/dialogues/DialoguesPage.tsx
> +      </AnalyticsContext>
```suggestion
      </AnalyticsContext>
```
```suggestion
      </AnalyticsContext>}
```

2023-10-31 18:25 UTC, darkruby501 commented on packages/lesswrong/server/resolvers/postResolvers.ts
> +  cacheMaxAgeMs: 1000 * 60 * 10, // 10 min
```suggestion
  cacheMaxAgeMs: 0

2023-10-31 18:26 UTC, darkruby501 commented on packages/lesswrong/components/dialogues/DialoguesPage.tsx
```suggestion
const renderMyDialogue = currentUser && myDialouges.length
```

2023-10-31 18:27 UTC, darkruby501 commented on packages/lesswrong/components/dialogues/DialoguesList.tsx
> +  const renderMyDialogues = myDialogues?.length
```suggestion
  const renderMyDialogues = !!currentUser && myDialogues?.length 
```

2023-10-31 19:22 UTC, ben-pace commented
I believe I have updated all the requested changes!

2023-10-31 19:25 UTC, b0b3rt commented on packages/lesswrong/components/dialogues/DialoguesList.tsx
> +  const renderMyDialogues = myDialogues?.length
@ben-pace still missing this one

2023-11-01 01:31 UTC, b0b3rt approved these changes

2023-11-01 01:39 UTC, merged